### ISSUE TITLE
Do a better job catching Tombo environment errors

### ISSUE THREAD

**Issue by SycamoreLeaf** [Chris-Kimmel/prsconv3#2]
Tombo depends on an h5py interface that has since been removed. This error should be caught and a more useful error message provided.

```bash
(sci-computing-env) [kimmel@owens-login04 prsconv3]$ python3 . per_read_stats tests/files/per_read_stats/*.tombo.per_read_stats out.csv
Traceback (most recent call last):
  File "/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 7, in <module>
    cli.engine_dict[args.which_kind].run(args)
  File "./engines/per_read_stats.py", line 99, in run
    .get_region_per_read_stats(reg)
  File "/users/PAS1405/kimmel/.conda/envs/sci-computing-env/lib/python3.7/site-packages/tombo/tombo_stats.py", line 3400, in get_region_per_read_stats
    zip(self.per_read_blocks[block_name]['read_ids'].value,
AttributeError: 'Dataset' object has no attribute 'value'
```

**Comment by SycamoreLeaf** [comment]
Mitigated with 1fa8fe6d28572eb7f8d86c94e0db1f4a646cbf16
